# Makefile

TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/../HDL/rising_edge.sv
TOPLEVEL = moore_rising_edge
MODULE = test_rising_edge

include $(shell cocotb-config --makefiles)/Makefile.sim
